export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";

export const SIGN_IN_FAILED ="SIGN_IN_FAILED";
export const SIGN_IN_SUCCESS ="SIGN_IN_SUCCESS";
export const SIGN_IN_REQUEST ="SIGN_REQUEST";

export const SIGN_OUT = "SIGN_OUT";

export const REMOVE_ERROR ='REMOVE_ERROR';

export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const SET_DATA = 'SET_DATA';